### ISSUE TITLE
problem with selenium-authenticated-proxy

### ISSUE THREAD

**Issue by yuval1973** [freezingdata/selenium-authenticated-proxy#2]
I can clearly see the following behavior happening around **70% of the cases**, which renders this extension almost useless. Looks like there is some timing issue here. It’s not clear why the popup shows up unless your extension is not completely initialized or something. 

![image](https://github.com/freezingdata/selenium-authenticated-proxy/assets/163681651/85213d1f-9e4b-4014-8f4b-9d7eb9aa4589)

**Comment by bubblegumsoldier** [comment]
Hi, I cannot reproduce it, therefore I need some help from you.

1. Please check when that happens the extension error log. For this go to "Manage Extension" and see under Chrome-Proxy if there is an "Error" field. If yes, please send the logs here.
![image](https://github.com/freezingdata/selenium-authenticated-proxy/assets/3788628/67cf7b93-1a55-4fba-a037-98fc2a8b9759)
2. If not, I see you have another extension running. Please make absolutely sure it doesn't interfere in some way. It might be some chrome default one, I know, just want you to make sure.
3. Please tell me if it only happens in non-headless mode. Please try headless=new as an option and check if the public IP is correct or not.
4. Please make sure the username and password is correct. If they are wrong that's the behaviour I would expect. It just pops up until it works.
5. Please let me know your chrome version + OS
6. Please try `SeleniumAuthenticatedProxy(..., use_legacy_extension=True)`
7. Is it happening with different proxies or just one?

**Comment by yuval1973** [comment]
Watch the repro I sent - it happens almost *all the time*
https://github.com/freezingdata/selenium-authenticated-proxy/assets/163681651/b0d7054a-f03b-4c9b-abcf-10b6b718b2b8

To your questions: 
1. there is no error in the "manage extensions" as you can see in the video
2. the other extension has nothing to do with yours and doesn't interfere. Also this happened before I used the other extension.
3. I cannot use headless at all so this isn't relevant
4. usernames/passwords are correct as they were given to me by the proxy. I have a pool of a few thousands pairs and every Chrome launch I'm creating a unique extension with a new username/password from the list. I then place it in a temp dir and after Chrome shutdown I delete the temp folder.
5. Chrome version is the latest as I have an auto mechanism. 
6. haven't tried `use_legacy_extension=True` - what will it do?
7. There is a very similar solution posted like what you did here
https://stackoverflow.com/questions/55582136/how-to-set-proxy-with-authentication-in-selenium-chromedriver-python
If I cannot fix your problem I'll try to implement this one although I really prefer to use your solution as it's cleaner. But right now I'm stuck as this almost never works due to this timing issue. My code is very simple and looks like that:

```
proxy_helper = SeleniumAuthenticatedProxy(proxy_url = proxyaddr, tmp_folder = ext_proxy_path)
proxy_helper.enrich_chrome_options(options)
driver = webdriver.Chrome(options = options)
driver.get(url)

```

maybe I just need to sleep for 3 seconds before doing the get() I don't know, but right now I'm kind of stuck

**Comment by yuval1973** [comment]
I tried doing the use_legacy_extension=True but it didn't help. I suspect, though not sure, that this might repro more easily if you run multiple Chrome instances concurrently like I do. Try automatically running 5 or 7 instances at the same time using a script and you might be able repro this. I suspect the auth dialog will automatically show up if the browser isn't active despite the fact that the extension does have the necessary data to provide for the auth request. Again I'm not sure but it's worth trying

**Comment by bubblegumsoldier** [comment]
> Watch the repro I sent - it happens almost _all the time_ https://github.com/freezingdata/selenium-authenticated-proxy/assets/163681651/b0d7054a-f03b-4c9b-abcf-10b6b718b2b8
> 
> To your questions:
> 
> 1. there is no error in the "manage extensions" as you can see in the video
> 2. the other extension has nothing to do with yours and doesn't interfere. Also this happened before I used the other extension.
> 3. I cannot use headless at all so this isn't relevant
> 4. usernames/passwords are correct as they were given to me by the proxy. I have a pool of a few thousands pairs and every Chrome launch I'm creating a unique extension with a new username/password from the list. I then place it in a temp dir and after Chrome shutdown I delete the temp folder.
> 5. Chrome version is the latest as I have an auto mechanism.
> 6. haven't tried `use_legacy_extension=True` - what will it do?
> 7. There is a very similar solution posted like what you did here
>    https://stackoverflow.com/questions/55582136/how-to-set-proxy-with-authentication-in-selenium-chromedriver-python
>    If I cannot fix your problem I'll try to implement this one although I really prefer to use your solution as it's cleaner. But right now I'm stuck as this almost never works due to this timing issue. My code is very simple and looks like that:
> 
> ```
> proxy_helper = SeleniumAuthenticatedProxy(proxy_url = proxyaddr, tmp_folder = ext_proxy_path)
> proxy_helper.enrich_chrome_options(options)
> driver = webdriver.Chrome(options = options)
> driver.get(url)
> ```
> 
> maybe I just need to sleep for 3 seconds before doing the get() I don't know, but right now I'm kind of stuck

I cannot reproduce the issues with the proxies I have at hand unfortunately. Also running multiple ones in parallel. However I would recommend trying the "sleep" method. The link you sent, I used originally as guidance. Due to limited time and me not being able to properly reproduce it, I would suggest that instead of writing everything from scratch you can also fork the repo and try to fix it there. I could imagine that being a bit quicker than implementing it from scratch again. Sorry that I cannot help. Not sure how to fix it at the moment.
